{ bid: 4996,
  beer_name: 'Punkin Ale',
  beer_label: 'https://untappd.akamaized.net/site/beer_logos/beer-_4996_sm.jpeg',
  beer_abv: 7,
  beer_ibu: 28,
  beer_description: 'A full-bodied brown ale with smooth hints of pumpkin and brown sugar. We brew our Punkin Ale with pumpkin meat, brown sugar and spices. As the season cools, this is the perfect beer to warm up with.\nPunkin Ale is named after the seriously off-centered southern Delaware extravaganza Punkin Chunkin (check out some of these Discovery Channel videos of Punkin Chunkin, you gotta see it to believe it!). In fact, Punkin Ale made its debut as it claimed first prize in the 1994 Punkin Chunkin Recipe Contest. Yes, that was a full 6 months before we even opened our doors for business!',
  created_at: 'Sat, 21 Aug 2010 09:26:35 +0000',
  beer_style: 'Pumpkin / Yam Beer',
  auth_rating: 0,
  wish_list: false,
  in_production: 1 },false,